# Generated by Django 4.2.5 on 2023-09-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Администрация',
                'verbose_name_plural': 'Администрация',
            },
        ),
        migrations.CreateModel(
            name='GovernmentEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Госслужащий',
                'verbose_name_plural': 'Госслужащие',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('text_of_question', models.TextField(verbose_name='Текст вопроса')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.administration', verbose_name='PK чиновника')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
